'use client'

import { useState } from 'react'
import { ArrowRight, BriefcaseBusiness, ChevronDown, Grid2X2, MapPin, Menu, MessageCircle, Search, Sparkles, Users, X } from 'lucide-react'

const talent = [
  { name: 'Ava Mitchell', role: 'Product Designer', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Okaef8ev2VcoFd27h8qrlZvxpncWbB.png', tags: ['Figma', 'Framer', 'Research'] },
  { name: 'Noah Williams', role: 'Software Developer', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-2EaspMMJYWDafBATeNhc7NWc6Sza0w.png', tags: ['React', 'TypeScript', 'AI'] },
  { name: 'Mia Thompson', role: 'Creative Strategist', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-EnTagLJDxgGgi9mkb1zBGWvPopJCqs.png', tags: ['Brand', 'Content', 'Growth'] },
  { name: 'Ethan Brooks', role: 'Data Analyst', image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-zsFf7GogxBXbZlBWx95WQP1h2bjoTQ.png', tags: ['SQL', 'Python', 'Insight'] },
]

const categories = ['Developer', 'UI Designer', 'Project Manager', 'Creative', 'Data & AI', 'Leadership']
const faqs = ['How does LearnFlow personalize my path?', 'Can I learn with a busy schedule?', 'Is LearnFlow free to start?', 'Can teams use LearnFlow together?']

export default function HomePage() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [category, setCategory] = useState('UI Designer')
  const [activeFaq, setActiveFaq] = useState(0)

  return (
    <main className="overflow-hidden bg-[#fbfbfc] text-[#1f2530]">
      <header className="fixed left-0 right-0 top-0 z-50 border-b border-[#dce2ea]/70 bg-[#fbfbfc]/85 backdrop-blur-xl">
        <div className="mx-auto flex h-[76px] max-w-[1240px] items-center justify-between px-5 lg:px-8">
          <a href="#top" className="flex items-center gap-2 text-[20px] font-semibold tracking-[-.06em]" aria-label="LearnFlow home"><span className="grid size-8 place-items-center rounded-[10px] bg-[#146bff] text-sm font-bold text-white">L</span>Learn<span className="text-[#146bff]">Flow</span></a>
          <nav className="hidden items-center gap-8 text-[13px] text-[#667085] md:flex"><a href="#discover" className="hover:text-[#146bff]">Discover paths</a><a href="#method" className="hover:text-[#146bff]">How it works</a><a href="#stories" className="hover:text-[#146bff]">Stories</a><a href="#faq" className="hover:text-[#146bff]">FAQ</a></nav>
          <div className="hidden items-center gap-4 md:flex"><a href="/login" className="text-[13px] font-medium text-[#667085]">Sign in</a><a href="/register" className="flex items-center gap-3 rounded-full border border-[#146bff] px-4 py-2 text-[13px] font-semibold text-[#146bff] hover:bg-[#146bff] hover:text-white">Start learning <span className="grid size-6 place-items-center rounded-full bg-[#146bff] text-white"><ArrowRight className="size-3.5" /></span></a></div>
          <button className="grid size-10 place-items-center rounded-full border border-[#dce2ea] md:hidden" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X /> : <Menu />}</button>
        </div>
        {menuOpen && <nav className="flex flex-col gap-5 border-t border-[#dce2ea] bg-[#fbfbfc] px-5 py-6 text-sm font-semibold md:hidden"><a href="#discover" onClick={() => setMenuOpen(false)}>Discover paths</a><a href="#method" onClick={() => setMenuOpen(false)}>How it works</a><a href="#stories" onClick={() => setMenuOpen(false)}>Stories</a><a href="/register">Start learning</a></nav>}
      </header>

      <section id="top" className="relative bg-[radial-gradient(circle_at_50%_8%,#b9a4ff_0%,#e8e2ff_24%,#fbfbfc_58%)] px-5 pb-20 pt-32 lg:px-8 lg:pt-36">
        <div className="mx-auto max-w-[1240px] text-center"><div className="mx-auto flex w-fit items-center gap-2 rounded-full bg-white px-4 py-2 text-xs font-medium text-[#526078] shadow-[0_8px_25px_rgba(89,76,170,.1)]"><Sparkles className="size-4 text-[#146bff]" /> Your intelligent learning space</div><h1 className="mx-auto mt-8 max-w-[850px] text-[clamp(3.3rem,7vw,6.8rem)] font-semibold leading-[.92] tracking-[-.085em] text-[#073473]">Showcase your <span className="text-[#146bff]">potential.</span><br />Build what&apos;s next.</h1><p className="mx-auto mt-6 max-w-[520px] text-[15px] leading-6 text-[#596579]">Create momentum with guided learning paths, practical projects, and an AI coach that knows where you want to go.</p><div className="mx-auto mt-8 flex max-w-[630px] flex-col gap-3 rounded-[22px] bg-white p-2 text-left shadow-[0_16px_50px_rgba(32,65,129,.13)] sm:flex-row sm:items-center"><div className="flex flex-1 items-center gap-3 px-4"><Search className="size-5 text-[#146bff]" /><input className="w-full bg-transparent py-3 text-sm outline-none placeholder:text-[#9aa4b2]" placeholder="e.g. product design, data, leadership" aria-label="Search learning paths" /><span className="hidden h-7 w-px bg-[#e5e9ef] sm:block" /><MapPin className="hidden size-5 text-[#146bff] sm:block" /><span className="hidden text-sm text-[#9aa4b2] sm:block">Anywhere</span></div><a href="#discover" className="rounded-full bg-[#146bff] px-7 py-3.5 text-center text-sm font-semibold text-white transition hover:bg-[#0758df]">Explore paths</a></div></div>
        <div className="mx-auto mt-14 grid max-w-[1240px] grid-cols-2 gap-3 sm:grid-cols-4 lg:gap-5">{talent.map((person, index) => <div key={person.name} className={`relative overflow-hidden rounded-[22px] ${index % 2 ? 'bg-[#dfe8ff]' : 'bg-[#fff0d8]'} ${index === 1 ? 'translate-y-5' : ''}`}><img src={person.image} alt={person.name} className="h-52 w-full object-cover object-center mix-blend-multiply sm:h-64 lg:h-72" /><div className="absolute inset-x-3 bottom-3 rounded-xl bg-white/90 p-3 backdrop-blur-sm"><p className="text-sm font-semibold">{person.name}</p><p className="text-xs text-[#778195]">{person.role}</p></div></div>)}</div>
      </section>

      <section id="discover" className="px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-[1240px]"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#146bff]">Find your next chapter</p><h2 className="mt-4 text-5xl font-semibold tracking-[-.07em] sm:text-7xl">Discover the<br /><span className="text-[#146bff]">paths that move you.</span></h2><p className="mx-auto mt-5 max-w-[530px] text-sm leading-6 text-[#667085]">Pick a direction, follow your curiosity, and let LearnFlow turn intention into a portfolio of real progress.</p></div><div className="mt-14 flex gap-2 overflow-x-auto border-b border-[#dce2ea] pb-0">{categories.map((item, index) => <button key={item} onClick={() => setCategory(item)} className={`flex shrink-0 items-center gap-2 border-b-2 px-4 py-4 text-sm ${category === item ? 'border-[#146bff] text-[#146bff]' : 'border-transparent text-[#7b8798]'}`}>{index === 0 ? <Grid2X2 className="size-4" /> : index === 1 ? <Sparkles className="size-4" /> : index === 2 ? <BriefcaseBusiness className="size-4" /> : <Users className="size-4" />}{item}</button>)}</div><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{talent.map((person, index) => <article key={`${person.name}-${category}`} className={`rounded-[20px] border p-5 transition hover:-translate-y-1 hover:shadow-xl ${index === 1 ? 'border-[#8bb4ff] bg-[#e6efff] shadow-[0_15px_35px_rgba(20,107,255,.12)]' : 'border-[#e3e7ee] bg-white'}`}><div className="mx-auto size-20 overflow-hidden rounded-full bg-[#e9edf4]"><img src={person.image} alt="" className="size-full object-cover" /></div><p className="mt-4 text-center text-xs text-[#f2b600]">★ <span className="text-[#647084]">4.9 (24)</span></p><h3 className="mt-3 text-center text-lg font-semibold tracking-[-.04em]">{person.name}</h3><p className="text-center text-xs text-[#7b8798]">{person.role}</p><div className="mt-5 flex flex-wrap justify-center gap-1.5">{person.tags.map(tag => <span key={tag} className="rounded-full border border-[#d8e0ee] px-2.5 py-1 text-[10px] text-[#68758a]">{tag}</span>)}</div></article>)}</div><div className="mt-10 text-center"><a href="/courses" className="inline-flex items-center gap-3 rounded-full border border-[#8bb4ff] px-5 py-2.5 text-sm font-semibold text-[#146bff]">View all paths <span className="grid size-6 place-items-center rounded-full bg-[#146bff] text-white"><ArrowRight className="size-3.5" /></span></a></div></div></section>

      <section id="method" className="bg-[#f4f7fb] px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto grid max-w-[1240px] items-center gap-14 lg:grid-cols-[1fr_1fr]"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#146bff]">How it works</p><h2 className="mt-4 max-w-xl text-5xl font-semibold leading-[.95] tracking-[-.075em] sm:text-7xl">A clearer route<br />to <span className="text-[#146bff]">capability.</span></h2><div className="mt-12 flex flex-col gap-4">{['Tell us what you want to become', 'Practice inside a path made for you', 'Build proof, confidence, and momentum'].map((step, index) => <div key={step} className="flex items-center gap-4 rounded-2xl bg-white p-4 shadow-[0_10px_30px_rgba(28,49,80,.06)]"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-[#e3ecff] text-sm font-semibold text-[#146bff]">0{index + 1}</span><div><p className="font-semibold">{step}</p><p className="mt-1 text-xs text-[#7b8798]">AI guidance, human pace, measurable progress.</p></div></div>)}</div></div><div className="relative min-h-[420px]"><div className="absolute inset-8 rounded-full border border-[#bdd3ff] bg-[#edf3ff]" /><div className="absolute left-[18%] top-[12%] w-[55%] overflow-hidden rounded-[28px] bg-[#15376d] shadow-2xl"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-dFINPVb73PHSPoJNHfxa2izPhqIeBy.png" alt="Learner working through a guided learning path" className="h-[330px] w-full object-cover opacity-90" /></div><div className="absolute bottom-8 left-0 rounded-2xl bg-white p-5 shadow-xl"><p className="text-3xl font-semibold text-[#146bff]">10k+</p><p className="text-xs text-[#667085]">active learners</p></div><div className="absolute right-0 top-24 rounded-2xl bg-white p-5 shadow-xl"><MessageCircle className="size-6 text-[#146bff]" /><p className="mt-3 font-semibold">AI coach online</p><p className="text-xs text-[#667085]">Ready when you are.</p></div></div></div></section>

      <section id="stories" className="px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-[1240px]"><div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="rounded-[28px] bg-[#202733] p-8 text-white sm:p-14"><p className="text-sm text-white/55">Maya K. <span className="mx-2">•</span> Product designer</p><blockquote className="mt-12 max-w-2xl text-4xl font-semibold leading-[1.02] tracking-[-.065em] sm:text-6xl">“I stopped collecting tabs and started finishing things.”</blockquote><a href="/register" className="mt-12 inline-flex items-center gap-3 rounded-full bg-white px-5 py-3 text-sm font-semibold text-[#202733]">Start your path <ArrowRight className="size-4" /></a></div><div className="overflow-hidden rounded-[28px] bg-[#dce8ff]"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-Q4X2OIfitozBhjUkYueL49DrWQE13B.png" alt="LearnFlow community and partner logos" className="h-full min-h-[360px] w-full object-cover mix-blend-multiply" /></div></div></div></section>

      <section id="faq" className="bg-[radial-gradient(circle_at_50%_0%,#cfc4ff,#f7f7ff_40%,#fbfbfc_78%)] px-5 py-24 lg:px-8 lg:py-32"><div className="mx-auto max-w-[980px]"><div className="text-center"><h2 className="text-5xl font-semibold tracking-[-.07em] sm:text-7xl">Questions,<br /><span className="text-[#146bff]">answered.</span></h2></div><div className="mt-14 grid gap-3 md:grid-cols-2">{faqs.map((question, index) => <div key={question} className={`rounded-2xl border p-5 ${activeFaq === index ? 'border-[#8bb4ff] bg-[#eaf1ff] shadow-[0_15px_35px_rgba(20,107,255,.1)]' : 'border-[#dce2ea] bg-white/80'}`}><button className="flex w-full items-center justify-between text-left font-semibold" onClick={() => setActiveFaq(activeFaq === index ? -1 : index)}><span><span className="mr-3 text-xs text-[#146bff]">0{index + 1}</span>{question}</span><ChevronDown className={`size-4 text-[#146bff] transition ${activeFaq === index ? 'rotate-180' : ''}`} /></button>{activeFaq === index && <p className="mt-4 pl-7 text-sm leading-6 text-[#667085]">LearnFlow combines an adaptive plan, focused practice, and an AI coach that keeps the next best action clear without overwhelming you.</p>}</div>)}</div><div className="mt-16 rounded-[28px] bg-white/80 p-8 text-center shadow-[0_15px_50px_rgba(107,90,205,.12)] sm:p-14"><h3 className="text-3xl font-semibold tracking-[-.055em] sm:text-5xl">Your next chapter starts here.</h3><p className="mx-auto mt-4 max-w-lg text-sm leading-6 text-[#667085]">Join ambitious learners building the skills and proof their future deserves.</p><a href="/register" className="mt-7 inline-flex items-center gap-3 rounded-full bg-[#146bff] px-6 py-3.5 text-sm font-semibold text-white">Join LearnFlow <ArrowRight className="size-4" /></a></div></div></section>

      <footer className="bg-[#e6eaff] px-5 py-12 lg:px-8"><div className="mx-auto grid max-w-[1240px] gap-10 md:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><a href="#top" className="text-2xl font-semibold tracking-[-.07em] text-[#146bff]">LearnFlow</a><p className="mt-4 max-w-xs text-sm leading-6 text-[#667085]">A calmer, smarter place to become exceptionally good at what matters to you.</p></div><div><h4 className="font-semibold">Explore</h4><div className="mt-4 flex flex-col gap-3 text-sm text-[#667085]"><a href="#discover">Learning paths</a><a href="/courses">Course library</a><a href="#stories">Learner stories</a></div></div><div><h4 className="font-semibold">Company</h4><div className="mt-4 flex flex-col gap-3 text-sm text-[#667085]"><a href="#method">How it works</a><a href="#faq">FAQ</a><a href="/admin">Admin portal</a></div></div><div><h4 className="font-semibold">Get started</h4><div className="mt-4 flex flex-col gap-3 text-sm text-[#667085]"><a href="/login">Sign in</a><a href="/register">Create account</a><span>© 2026 LearnFlow</span></div></div></div></footer>
    </main>
  )
}
