'use client'

import { ArrowLeft, UserRound } from 'lucide-react'
import { FormEvent, useState } from 'react'

export default function RegisterPage() {
  const [submitted, setSubmitted] = useState(false)
  function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitted(true) }
  return <main className="flex min-h-screen items-center justify-center bg-[#f7f9f8] px-6 py-10 text-[#172b2a]"><div className="w-full max-w-md"><a href="/" className="mb-10 inline-flex items-center gap-2 text-sm font-semibold text-[#647672] hover:text-[#147761]"><ArrowLeft className="size-4" /> Back to LearnFlow</a><div className="rounded-3xl border border-[#e0ebe6] bg-white p-7 shadow-[0_20px_60px_rgba(39,91,77,0.08)] sm:p-9"><div className="grid size-11 place-items-center rounded-2xl bg-[#e7f5f0] text-[#147761]"><UserRound className="size-5" /></div><h1 className="mt-6 text-3xl font-bold tracking-[-0.05em]">Start your learning journey</h1><p className="mt-2 text-sm leading-6 text-[#778783]">Create a student account and make progress that sticks.</p>{submitted && <div className="mt-5 rounded-xl bg-[#eaf7f1] px-4 py-3 text-sm text-[#147761]">Registration UI is ready. Connect Better Auth to persist your account.</div>}<form onSubmit={handleSubmit} className="mt-7 flex flex-col gap-4"><label className="flex flex-col gap-2 text-sm font-semibold">Full name<input required placeholder="Jordan Miller" className="h-11 rounded-xl border border-[#dce8e3] bg-[#fbfdfc] px-3 text-sm outline-none focus:border-[#77b9a8] focus:ring-2 focus:ring-[#dff2eb]" /></label><label className="flex flex-col gap-2 text-sm font-semibold">Email address<input required type="email" placeholder="you@example.com" className="h-11 rounded-xl border border-[#dce8e3] bg-[#fbfdfc] px-3 text-sm outline-none focus:border-[#77b9a8] focus:ring-2 focus:ring-[#dff2eb]" /></label><label className="flex flex-col gap-2 text-sm font-semibold">Password<input required minLength={8} type="password" placeholder="At least 8 characters" className="h-11 rounded-xl border border-[#dce8e3] bg-[#fbfdfc] px-3 text-sm outline-none focus:border-[#77b9a8] focus:ring-2 focus:ring-[#dff2eb]" /></label><button className="mt-2 h-11 rounded-xl bg-[#17856d] text-sm font-semibold text-white transition hover:bg-[#126b58]">Create student account</button></form><p className="mt-7 text-center text-sm text-[#778783]">Already have an account? <a href="/login" className="font-semibold text-[#147761]">Sign in</a></p></div></div></main>
}
