'use client'

import { ArrowLeft, LockKeyhole, Mail } from 'lucide-react'
import { FormEvent, useState } from 'react'

export default function LoginPage() {
  const [submitted, setSubmitted] = useState(false)
  function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitted(true) }
  return <main className="flex min-h-screen items-center justify-center bg-[#f7f9f8] px-6 py-10 text-[#172b2a]"><div className="w-full max-w-md"><a href="/" className="mb-10 inline-flex items-center gap-2 text-sm font-semibold text-[#647672] hover:text-[#147761]"><ArrowLeft className="size-4" /> Back to LearnFlow</a><div className="rounded-3xl border border-[#e0ebe6] bg-white p-7 shadow-[0_20px_60px_rgba(39,91,77,0.08)] sm:p-9"><div className="grid size-11 place-items-center rounded-2xl bg-[#e7f5f0] text-[#147761]"><LockKeyhole className="size-5" /></div><h1 className="mt-6 text-3xl font-bold tracking-[-0.05em]">Welcome back</h1><p className="mt-2 text-sm leading-6 text-[#778783]">Sign in to continue your learning journey.</p>{submitted && <div className="mt-5 rounded-xl bg-[#fff7e9] px-4 py-3 text-sm text-[#936322]">Auth is ready to connect to Neon. Add your Better Auth secret to enable sign in.</div>}<form onSubmit={handleSubmit} className="mt-7 flex flex-col gap-5"><label className="flex flex-col gap-2 text-sm font-semibold">Email address<div className="relative"><Mail className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#9aa8a4]" /><input required type="email" placeholder="you@example.com" className="h-11 w-full rounded-xl border border-[#dce8e3] bg-[#fbfdfc] pl-10 pr-3 text-sm outline-none focus:border-[#77b9a8] focus:ring-2 focus:ring-[#dff2eb]" /></div></label><label className="flex flex-col gap-2 text-sm font-semibold">Password<input required minLength={8} type="password" placeholder="Enter your password" className="h-11 w-full rounded-xl border border-[#dce8e3] bg-[#fbfdfc] px-3 text-sm outline-none focus:border-[#77b9a8] focus:ring-2 focus:ring-[#dff2eb]" /></label><button className="mt-1 h-11 rounded-xl bg-[#163b38] text-sm font-semibold text-white transition hover:bg-[#20524d]">Sign in</button></form><p className="mt-7 text-center text-sm text-[#778783]">New to LearnFlow? <a href="/register" className="font-semibold text-[#147761]">Create an account</a></p></div></div></main>
}
